# -*- coding: utf-8 -*-
"""ScriptsDadosAnalytica2024PedroArthurSantosGama

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vpdGodVasw3f6uvfKx-QQEwGWGy_CB28
"""

pip install pandas matplotlib

import pandas as pd
import matplotlib.pyplot as plt

pd.set_option('display.float_format', lambda x: '%.2f' % x)


dados = pd.read_csv('InvestimentoMacrorregioes.csv')


mapeamento_macrorregioes = {
    'Norte': ['AC', 'AP', 'AM', 'PA', 'RO', 'RR', 'TO'],
    'Nordeste': ['AL', 'BA', 'CE', 'MA', 'PB', 'PE', 'PI', 'RN', 'SE'],
    'Sudeste': ['ES', 'MG', 'RJ', 'SP'],
    'Sul': ['PR', 'RS', 'SC'],
    'Centro-Oeste': ['DF', 'GO', 'MT', 'MS']
}


dados['macrorregiao'] = dados['sigla_uf'].apply(lambda x: next(regiao for regiao, sigla_uf in mapeamento_macrorregioes.items() if x in sigla_uf))



dados_agrupados = dados.groupby(['macrorregiao', 'ano'])['GASTOS'].sum().reset_index()



macrorregiao = 'Centro-Oeste'
dados_macrorregiao_escolhida = dados_agrupados[dados_agrupados['macrorregiao'] == macrorregiao]


plt.ticklabel_format(style='plain', axis='y')
plt.plot(dados_macrorregiao_escolhida['ano'], dados_macrorregiao_escolhida['GASTOS'], marker='o', label=macrorregiao)
plt.xlabel('Ano')
plt.ylabel('Gastos em Educação')
plt.title(f'Evolução dos Gastos em Educação na Macrorregião {macrorregiao}')
plt.legend()
plt.show()